### ISSUE TITLE
Add minimum version specs to documentation

### ISSUE THREAD

**Issue by roopikarisam** [minicomp/wiki#12]
(Moved this here from the Wax repo)

Didn't realize I didn't have the version of Bundler (v. 2.0) that I needed until I couldn't run jekyll serve because v. 1.16.1 is the example in the documentation (https://minicomp.github.io/wiki/wax/system-requirements/) and the error didn't indicate the version was the problem. Sorted it out quickly but may be an obstacle to those who haven't worked w/ Jekyll before. Consider adding minimum versions to the documentation.

**Comment by mnyrop** [comment]
Fixed in wax itself by not requiring bundler explicitly. Thanks for the heads up!
