### ISSUE TITLE
Fix library link

### ISSUE THREAD

**Issue by mnyrop** [minicomp/wiki#16]
Broken according to html-proofer (404):

> - ./_site/wiki/wax/index.html
>   *  External link https://library.columbia.edu/news/events/event.html?guid=CAL-00bb9e25-6667531c-0166-695e8946-00001777events%40columbia.edu&returnlinkurl=/content/libraryweb/research/workshops&returnlinktext=Workshops failed: 404 No error
> rake aborted!
> HTML-Proofer found 1 failure!

**Comment by awoods** [comment]
I ran into this as well... wondering what the workshop was about.

**Comment by mnyrop** [comment]
Hey @elotroalex, do you have a link/materials for your workshop that we can use to replace this broken one?

**Comment by elotroalex** [comment]
will look. and if not, create one or delete the link
